
#type: args
# for debug setting
train:
  epochs: 1 #diminished
  batch_size: 4 #diminished
  lr: 1.0e-3

diffusion:
  layers: 2 #diminished
  channels: 16 
  nheads: 8
  diffusion_embedding_dim: 16 #diminished
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 2 #diminished
  schedule: "quad"

model:
  is_unconditional: 0
  timeemb: 64
  featureemb: 16
  target_strategy: "forecast"
