
#type: args

train:
  epochs: 10 #diminished
  batch_size: 8 #diminished
  lr: 1.0e-3

diffusion:
  layers: 2 #diminished
  channels: 64 
  nheads: 8
  diffusion_embedding_dim: 64 #diminished
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 20 #diminished
  schedule: "quad"

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "random"
